### ISSUE TITLE
Multiple Url's?

### ISSUE THREAD

**Issue by jzeltman** [amccloud/storybook-addons-abstract#13]
Is it possible to add multiple URL's? An example use-case, a button with a default and hover state.

**Comment by amccloud** [comment]
👋 Heyo,

I'm still working on improving this but do have something you can try. The goal is to avoid the labor or creating a share for each state

If you can use collections to document components, each layer in the collection can be a state. This addon will automatically keep things in syncs as long as the story is roughly named the same as the layer in the collection:

![image](https://user-images.githubusercontent.com/38463/78077733-c60b3f00-735d-11ea-91a3-821eecb1467a.png)

> Note: While the names are exact in the example above, the artboard could be called `Icon No Tint Label` and everything would work the same. Only alphanumeric characters are considered

**Comment by jzeltman** [comment]
@amccloud Thanks for the update.  don't control the design file as I work on the dev team vs design team. I'll see what I can do. 👍
