### ISSUE TITLE
Links to Artboards fail to load

### ISSUE THREAD

**Issue by helenezspeer** [amccloud/storybook-addons-abstract#19]
When I use a share link to an Artboard, the embed fails to load. However, I have been able to view a share link to a Collection. Should this work with artboards?

**Comment by helenezspeer** [comment]
I may have misunderstood -- it looks like the link should be for a "layer". I can't find documentation in Abstract on how to get the share link of a layer. Would you be willing to help?

**Comment by helenezspeer** [comment]
My response from Abstract is that you can create a share link to a Collection or to an Artboard, but not to a Layer. So I'm back here: Is there a way for me to get my link to an artboard to load?

**Comment by amccloud** [comment]
@helenezspeer Heyo sorry for the late reply. I’m out on PTO this week

The terminology for layer and artboard is confusing. Artboard is usually the top level layer and I think is what you are looking for, but it could also be a Symbol or something else 

While I do typically recommend linking stories with a collection to avoid linking each story manually to multiple layers. If you navigate to any artboard/layer in abstract, you can grab a share link to use with this plugin:

https://help.abstract.com/collaboration/share-designs/

**Comment by helenezspeer** [comment]
Sorry to bug you while you're on pto! It seems like my issue is with the "?find=[story name]. If I remove that from the query string, the artboard appears. What in Abstract is supposed to match the story name to make the right thing appear? I think that's my problem.

**Comment by amccloud** [comment]
@helenezspeer `find` is automatically set to the story name for you but only works on collection shares, as it’s to find a layer in a collection

If you have a story with two examples “Button” and “Button-primary”, you can link that story to a collection with “Button” and “Button Primary” from Abstract and this addon will automatically find and display the corresponding layer for you when you view the Button-primary story

Casing and spacing does not matter, as long as the names of items in the story roughly match the name of items in the collection everything should work

**Comment by helenezspeer** [comment]
That works! I think a good enhancement would be to be able to declare a layer name in the story code rather than have to make the story name match the collection layer name. I have a meeting later to discuss who is going to have to change their names... :)

Thank you for your help!

**Comment by helenezspeer** [comment]
I found something that doesn't work for me. The story is called "primary", and the src of the iframe has the query ?find=supplier--primary (because the story "primary" is under "supplier"). Naming a collection layer "supply--primary" or "supply primary" does not make the appropriate artboard load. What should I name the collection layer so that it matches this particular story?

**Comment by amccloud** [comment]
Name mapping would be nice and it is something I’d like to explore

Because we usually have one collection per story file, “supplier” and things before the dashes are currently not included in the search

If you could name the layer “Primary” that would work

**Comment by helenezspeer** [comment]
Thank you!
