### ISSUE TITLE
Does it only work with public layouts?

### ISSUE THREAD

**Issue by felipemrodrigues** [amccloud/storybook-addons-abstract#2]
I'd like to use it with layout of my organization. Is there a way to do that? It works properly with a public layout.

**Comment by amccloud** [comment]
@felipemrodrigues thanks for the feedback! Only [public share links are supported by the Abstract embed](https://sdk.goabstract.com/docs/embed/) at the moment. Once the embed supports private shares this plugin will also support it

**Comment by amccloud** [comment]
@felipemrodrigues Sorry about the delay on this. Embeds for private shares will now work if you've previously logged into app.abstract.com before viewing the embed

**Comment by MichiNetlight** [comment]
@amccloud Hi! Private share only work on Firefox for me but fail to load in chrome with Error 401 although I've previously logged into app.abstract.com. Opening the link directly (e.g. https://share.goabstract.com/4a84b5b2-2438-4bd7-...) works just fine. 
Do have have any advice on how to tackle this?

**Comment by signed** [comment]
Running into the same problem as @MichiNetlight

**Comment by signed** [comment]
Did a bit of testing and it looks like it is related to the new [default cookie settings](https://www.chromium.org/updates/same-site/test-debug) introduced in chrome 84.

You can open _chrome://flags/_ and set _same-site-by-default-cookies_ to **disabled**.
:warning:Make sure you understand the security implications, there is a reason why they are enabling it by default.:warning:
