### ISSUE TITLE
JSX in v5.1.0

### ISSUE THREAD

**Issue by psmyrek** [amccloud/storybook-addons-abstract#25]
Hi @amccloud  🙂 
First of all - thank you for creating this nice and useful Storybook addon!

Recently I've tried to upgrade from `v5.0.7` to `v5.1.0`, but then I've got the following error during building my Storybook:

```
ERROR in ./node_modules/storybook-addons-abstract/dist/register.js 24:13
Module parse failed: Unexpected token (24:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       var active = _ref.active,
|           key = _ref.key;
>       return <_components.AddonPanel active={active} key={key}>
|         <_panel.Panel />
|       </_components.AddonPanel>;
```

After downloading `storybook-addons-abstract` from npm I saw that in `dist/register.js` between `v5.0.7` and `v5.1.0` there is the following change: in the former one JSX is transpilled to plain JS, but in latest version there is JSX:

```
<_components.AddonPanel active={active} key={key}>
  <_panel.Panel />
</_components.AddonPanel>
```

In my project I'm not using neither React nor JSX, so could you please provide a JSX-free package version of your addon in npm?

**Comment by engdahl** [comment]
I'm getting exactly the same issue. Seems like this is an oversight with the update or what should we do to rectify it?

**Comment by amccloud** [comment]
@engdahl can you try the pre-release of 6.0.0 https://github.com/amccloud/storybook-addons-abstract/pull/24#issuecomment-670138175

**Comment by amccloud** [comment]
Closed in https://github.com/amccloud/storybook-addons-abstract/pull/24, you can now upgrade addon to 6.0.0 to fix jsx issue
