### ISSUE TITLE
DOMException cannot read local/sessionStorage from Window

### ISSUE THREAD

**Issue by amccloud** [amccloud/storybook-addons-abstract#27]
I get the same error but in my case it fails and the abstract tab doesn't render anything. It could be due a change on Abstract tough. Here's more console errors:

<img width="1664" alt="Screenshot 2020-10-19 at 16 10 01" src="https://user-images.githubusercontent.com/4297022/96462304-b6821380-1225-11eb-8437-85ada9888330.png">

The weird thing is that I'm using the same Share Abstract URL than the one from the demo.

_Originally posted by @luciomartinez in https://github.com/amccloud/storybook-addons-abstract/issues/26#issuecomment-712176710_

**Comment by amccloud** [comment]
@luciomartinez this is the first report I've seen of this. Can you tell me a bit more about your environment:

- Browser version
- Do you have ad blocker installed?
- Is localStorage or sessionStorage full?

Seems this might be related to a Chrome setting you may have enabled. This exception is thrown when the "Block third-party cookies and site data" checkbox is set in Content Settings.
To find the setting, open Chrome settings, type "third" in the search box, click the Content Settings button, and view the fourth item under Cookies.

**Comment by luciomartinez** [comment]
<img width="1478" alt="Screenshot 2021-02-05 at 10 04 17" src="https://user-images.githubusercontent.com/4297022/107012600-855c2d80-6799-11eb-99f9-094c785483cd.png">

You were precisely right! Left is third cookies enabled and right is disabled. In other words, Chrome Incognito doesn't work unless explicitly allowing third party cookies, but regular (non-icognito) works out of the box.

I feel like it's worth to mention in the README. What do you reckon?
