### ISSUE TITLE
How can I set this up when using CSF format?

### ISSUE THREAD

**Issue by engdahl** [amccloud/storybook-addons-abstract#3]
Is it possible to set up Abstract addon using CSF?

This is not working:

```
export default {
  component: Button,
  title: 'Button',
  parameters: {
    abstract: {
      url: 'https://share.goabstract.com/xxxxxxx'
    }
  }
}

export const button = () => <Button onClick={() => {}} label="Button" />
```

**Comment by keighleykodric** [comment]
☝️

**Comment by amccloud** [comment]
@engdahl @keighleykodric I converted the example from the readme to CSF and it appears to be working for me. I’ll update the example in readme and provide a live example

In the meantime can you tell me what you see when you use your CSF code above? Does the Abstract panel not display at all?

**Comment by amccloud** [comment]
Here is an example:

https://storybook-addons-abstract.amccloud.now.sh/?path=/story/blog-csf--blog-index

You can use the `Story` tab to view the source. Let me know if that helps 👍
