### ISSUE TITLE
Support linking to an individual symbol

### ISSUE THREAD

**Issue by mhatvan** [amccloud/storybook-addons-abstract#39]
To be able to check if the design and storybook implementation are a 1:1 match, it would be great to link to a symbol instead of the whole collection.

**Comment by mhatvan** [comment]
Bump

**Comment by mhatvan** [comment]
Not stale, reopen please.

**Comment by amccloud** [comment]
@mhatvan thanks for the suggestion. I’m open to reviewing a PR for this

Right now the suggested workflow is a collection per component. That was done so you don’t need to connect each visual state to each story

As long as layers in the collection and stories are named the same everything should sync up 1:1 with a lot less work

**Comment by mhatvan** [comment]
Our designers are saying that this is a big overhead, which I can understand. They have all button variants as one collection, all badges, etc.

Splitting up each button into a single collection doesn't make any sense.

If you can tell me that the API theoretically supports linking to a symbol, then I would provide a PR for this.
