### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by mhatvan** [amccloud/storybook-addons-abstract#44]
The package still depends on react ^16.8.3, it would be great to support React 17 in order to avoid necessary resolutions on the user side to avoid potential https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

**Comment by amccloud** [comment]
@mhatvan thanks for the heads up. Will get an updated build out asap

**Comment by mhatvan** [comment]
Not stale, reopen please.
