### ISSUE TITLE
Need more details about Abstract share link

### ISSUE THREAD

**Issue by mlegait** [amccloud/storybook-addons-abstract#54]
Hi and thank you for this addon 🙂 

I've some questions related to the URL to use. In the documentation it's written:
> // Copy a collection or layer share url from Abstract

But if I use a share link from a collection, it doesn't work:
![image](https://user-images.githubusercontent.com/19664438/136207883-f05a6db0-a6b5-48d9-a431-d183b1a81ef0.png)
And there is this in the browser console:
![image](https://user-images.githubusercontent.com/19664438/136208004-66cbd415-7078-483f-b90a-f820b725e31e.png)
Is there a specific configuration to do in Abstract to make it work?

If I use a share link from something in the master branch, it works but the first layer is displayed instead of the one I want. 

As you can guess, I'm not a UX/UI designer used to Abstract, just a developer trying to make it work with Storybook.

So could you add more details in the documentation explaining how to get a proper share link, please? 

Thank you very much for your help 🙏

**Comment by amccloud** [comment]
@mlegait a share link to the collection should work. Can you try with a public share link or while you're logged into Abstract

**Comment by mlegait** [comment]
Thank you for your quick answer 🙂 

I finally found how to do it thanks to this documentation: https://help.abstract.com/hc/en-us/articles/360050380031-Share-your-designs 🎉 
You could maybe add the link to the README.md to help other users like me. 

Thank you again for this addon 😄
