### ISSUE TITLE
Plugin not compatible with Angular 7 & 11

### ISSUE THREAD

**Issue by akhileshThapliyal** [amccloud/storybook-addons-abstract#55]
I tried to install the addon and included the addon in main.js, but I am encountering the below error. Appreciate your prompt help and support. Please let me know if you require any additional documents. Thank You :)

ERROR in ./node_modules/storybook-addons-abstract/dist/register.js
Module not found: Error: Can't resolve 'react/jsx-runtime' in '/Users/akhilesht/Desktop/Research & Development/Angular/storybook/node_modules/storybook-addons-abstract/dist'
 @ ./node_modules/storybook-addons-abstract/dist/register.js 11:18-46
 @ ./node_modules/storybook-addons-abstract/register.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js ./node_modules/@storybook/addon-links/dist/register.js ./node_modules/@storybook/addon-docs/dist/register.js ./node_modules/@storybook/addon-controls/dist/register.js ./node_modules/@storybook/addon-actions/dist/register.js ./node_modules/@storybook/addon-backgrounds/dist/register.js ./node_modules/@storybook/addon-viewport/dist/register.js ./node_modules/@storybook/addon-toolbars/dist/register.js storybook-addons-abstract/register ./.storybook/generated-refs.js

ERROR in ./node_modules/storybook-addons-abstract/dist/panel.js
Module not found: Error: Can't resolve 'react/jsx-runtime' in '/Users/akhilesht/Desktop/Research & Development/Angular/storybook/node_modules/storybook-addons-abstract/dist'
 @ ./node_modules/storybook-addons-abstract/dist/panel.js 18:18-46
 @ ./node_modules/storybook-addons-abstract/dist/register.js
 @ ./node_modules/storybook-addons-abstract/register.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js ./node_modules/@storybook/addon-links/dist/register.js ./node_modules/@storybook/addon-docs/dist/register.js ./node_modules/@storybook/addon-controls/dist/register.js ./node_modules/@storybook/addon-actions/dist/register.js ./node_modules/@storybook/addon-backgrounds/dist/register.js ./node_modules/@storybook/addon-viewport/dist/register.js ./node_modules/@storybook/addon-toolbars/dist/register.js storybook-addons-abstract/register ./.storybook/generated-refs.js

![image](https://user-images.githubusercontent.com/7280745/139786393-adac512a-0a8f-4219-82c2-1e65c0d3b43e.png)

**Package JSON**

{
  "name": "storybook",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "docs:json": "compodoc -p ./tsconfig.json -e json -d .",
    "storybook": "npm run docs:json && start-storybook -p 6006",
    "build-storybook": "npm run docs:json && build-storybook"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.0.3",
    "@angular/common": "~11.0.3",
    "@angular/compiler": "~11.0.3",
    "@angular/core": "~11.0.3",
    "@angular/forms": "~11.0.3",
    "@angular/platform-browser": "~11.0.3",
    "@angular/platform-browser-dynamic": "~11.0.3",
    "@angular/router": "~11.0.3",
    "rxjs": "~6.6.0",
    "storybook-addons-abstract": "^6.2.1",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.3",
    "@angular/cli": "~11.0.3",
    "@angular/compiler-cli": "~11.0.3",
    "@babel/core": "^7.12.9",
    "@compodoc/compodoc": "^1.1.11",
    "@storybook/addon-actions": "^6.1.10",
    "@storybook/addon-essentials": "^6.1.10",
    "@storybook/addon-links": "^6.1.10",
    "@storybook/angular": "^6.1.10",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "babel-loader": "^8.2.2",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}

**Comment by amccloud** [comment]
This plugin only supports react right now
